---
title: "EPI 501 Dynamics of Infectious Disease (Review)"
author: "Mathew Kiang"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Table of Contents (reverse chronological)
- [**Common Error Messages**](./errors.html)

- Week 3 (Februrary 9, 2018)
    - Review session: 
        - Went over Week 1 and Week 2 slides in class, line-by-line. Please review those if you didn't attend the lab.
        - In addition, we spent a lot of time on the ebola time-varying transmission model. 
            - I made [a notebook to answer the two questions](./20180209_lab_session/ebola_questions.nb.html) we didn't have time for: (1) What happens when you delay intervention? (2) What happens when you change the rate of decay?
        - As a reminder, [I made an interactive infectious disease app you can play with](https://mkiang.shinyapps.io/DiseaseDynamics/). Play with parameters, especially the relationship between the latent period and the infectious period, to get a better sense of **when** we need a latent compartment.
- Week 2 (January 29, 2018)
    - [Ebola and SEIR models](./20180202_ebola/index.html) [[PDF](./20180202_ebola/20180202-ebola.pdf)] [[Code and Data Files](https://github.com/mkiang/epi501_review/tree/master/20180202_ebola/code)]
        - [SEIR model with case fatality ratio](./20180202_ebola/index.html#3)
        - [Plotting SEIR lines](./20180202_ebola/index.html#11)
        - [COunting total cases and total deaths](./20180202_ebola/index.html#13)
        - [Time-varying transmission](./20180202_ebola/index.html#18)
        - [Calculate changing $R_0$](./20180202_ebola/index.html#30)
        - [Time-varying beta](./20180202_ebola/index.html#38)

- Week 1 (January 22, 2018)
    - [Introduction to ODE models in `R`](./20180129_intro_odes/index.html) [[PDF](./20180129_intro_odes/20180129-intro-odes.pdf)] [[Code Files](https://github.com/mkiang/epi501_review/tree/master/20180129_intro_odes/code)]
        - [SIR code review](./20180129_intro_odes/index.html#7)
        - [Visualize your results](./20180129_intro_odes/index.html#54)
        - [Make an SI model](./20180129_intro_odes/index.html#64)
        - [Make an SIS model](./20180129_intro_odes/index.html#70)
        - [Make an SIR model with births/deaths](./20180129_intro_odes/index.html#73)
    - [Introduction to `R`, discrete time models, non-infectious ODE models.](./20180124_intro_to_R_headaches/index.html) 
    - Download [`headache_exercises.zip`](./exercises/01_headaches/headache_exercises.zip)
        - Or download the code here (not recommended):
            - [`discrete_births_and_deaths.R`](https://raw.githubusercontent.com/mkiang/epi501_review/master/exercises/01_headaches/discrete_births_and_deaths.R)
            - [`headache_discrete.R`](https://raw.githubusercontent.com/mkiang/epi501_review/master/exercises/01_headaches/headache_discrete.R)
            - [`headache_ode.R`](https://raw.githubusercontent.com/mkiang/epi501_review/master/exercises/01_headaches/headache_ode.R)
    - Annotated code:
        - For the [`headache_discrete.R`](./20180124_intro_to_R_headaches/anno_code/discrete_headaches.nb.html) file.
        - For the [`headache_ode.R`](./20180124_intro_to_R_headaches/anno_code/ode_headaches.nb.html) file.

- Week 0 (January 16, 2018) 
    - [Software Carpentry](https://swcarpentry.github.io/r-novice-gapminder/): Strongly recommend you do sections 0 to 3 if you've never used `R` before. This will get you up and running with the software and introduce you to RStudio.
    - [Swirl Tutorial](http://swirlstats.com/students.html): If you've never used `R` before, we highly recommend doing this tutorial and the SW tutorial (above).
    - [Super quick `R` Review](./spring_2017/jan25-intro-to-r/index.html): If you've used `R` in the past but need a refresher, this is a tutorial I made for Spring 2017. It is not nearly as thorough as the above two.
    - [Shiny app for ODE models](https://mkiang.shinyapps.io/DiseaseDynamics/): Example of what we'll be doing throughout the course.

## Source / Archive
- You can find the source code along with all class code and PDFs on [this project's GitHub page](https://github.com/mkiang/epi501_review).
- You can find slides from [Spring 2017 here](./spring_2017/index.html).